In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3, 4, 5])

In [5]:
import random
import numpy as np

# Generate a random integer between 1 and 10 using random module
print(random.randint(1, 10))

# Generate a 3x3 array of random integers between 1 and 10 using NumPy
rand_int = np.random.randint(1, 10, size=(3, 3))

# Print the random integer array
print("Random Integer Array:\n", rand_int)

9
Random Integer Array:
 [[3 8 8]
 [5 8 5]
 [8 7 3]]


In [6]:
rand_float = np.random.random((2,2))
print("Random Float Array:\n", rand_float)

Random Float Array:
 [[0.89586107 0.9974724 ]
 [0.39325099 0.77447379]]


In [7]:
normal_dist = np.random.randn(3, 3)
print("normal Distribution Array:\n", normal_dist)

normal Distribution Array:
 [[ 1.07500822  0.29528844 -0.06953621]
 [-0.70449717  0.42519179  0.58866997]
 [ 1.11906971 -2.63058313 -0.54408195]]


In [8]:
arr_arange = np.arange(1, 10, 1).reshape(3,3)
print("\nArange array (range with step):\n", arr_arange)


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np
arr_arange = np.arange(1, 10, 1).reshape(3, 3)
print("\nArange array (range with step):\n", arr_arange)
print("index [1, 2]:", arr_arange[1, 2])  
print("slice (rows 1 to 2, columns 1 to 2):\n", arr_arange[1:3, 0:2])  


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
index [1, 2]: 6
slice (rows 1 to 2, columns 1 to 2):
 [[4 5]
 [7 8]]


In [12]:
arr_arange = np.arange(1, 10, 1)
print("\nArange array (range with step):\n", arr_arange)
print("index ", arr_arange[5])
print("slice ", arr_arange[1:6])
print("slice ", arr_arange[:6])
print("slice ", arr_arange[2:])



Arange array (range with step):
 [1 2 3 4 5 6 7 8 9]
index  6
slice  [2 3 4 5 6]
slice  [1 2 3 4 5 6]
slice  [3 4 5 6 7 8 9]


In [13]:
arr_arange = np.arange(1, 10, 1).reshape(3,3)
print("\nArange array (range with step):\n", arr_arange)
print(arr_arange[1])
print(arr_arange[1,1])
print(arr_arange[:,1])
print(arr_arange[::2,::2]) #[start=0:end=len(array):step=1]


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5
[2 5 8]
[[1 2]
 [4 5]]


In [14]:
arr1 = arr_arange[::2,::2]
print(arr1)
arr2 = arr_arange[:2:1,:2:1]
print(arr2)

[[1 3]
 [7 9]]
[[1 2]
 [4 5]]


In [15]:
arr1 = arr2 + 5
print(arr2)

[[1 2]
 [4 5]]


In [17]:
arr1 = arr2 + np.array([1,2])
print(arr1)
print(arr2)

[[2 4]
 [5 7]]
[[1 2]
 [4 5]]


In [18]:
l1 = [5,6,7,4, "Jay", False, (5,6)]

In [19]:
print(l1)

[5, 6, 7, 4, 'Jay', False, (5, 6)]


In [1]:
import pandas as pd
data = [10, 20, 30, 40, 50]
series1 = pd.Series(data)
print(series1)
print(series1[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
30


In [2]:
#two forms of Pandas - Series (1 dimension) and Data Frame(2 dimensions)
#Pandas
import pandas as pd


In [8]:
data = [10, 20, 30, 40, 50]
series1 = pd.Series(data)
print(series1) #This is an example of a series data type that is just a collection of one dimension data 
# That means only one collumn will be there with a numerical index

#to access values

print(series1[2])


0    10
1    20
2    30
3    40
4    50
dtype: int64
30


In [13]:
# Creating a Series from Python dictionary - to using dictionnaires to access the series #They use keys with string type not numerical
data = {'A':100, 'B':200, 'C':300}
series2 = pd.Series(data)
print(series2)
print(series2['A'])
print(series2['B']) #String index gets higher priority
print(series2.iloc[0]) #Accessing Series using a numeric value

A    100
B    200
C    300
dtype: int64
100
200
100


In [19]:
#Creating manual index. Customise index

data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
series4 = pd.Series(data, index=index) #index=index is the keyword to change the index
series4

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
#Creating an index that doesnt start by 0(zero)
#The default data type in Pandas is often 64-bit (e.g., int64, float64) because Pandas is designed for efficient handling of large datasets
# and 64-bit data types provide a balance between precision and performance.
data = [10, 20, 30, 40, 50]
#index = ['a', 'b', 'c', 'd', 'e']
index = range(101,106)
series4 = pd.Series(data, index=index) #index=index is the keyword to change the index
series4

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [24]:
#Changing the data type #The 32-bit format originated from older computing architectures and earlier systems that were designed for 32-bit processors. To understand where it came from, let's look into the evolution of computing and why 32-bit was widely used before 64-bit became the standard.
data = [10, 20, 30, 40, 50]
#index = ['a', 'b', 'c', 'd', 'e']
index = range(101,106)
series4 = pd.Series(data, index=index, dtype='int32', name="Number Series") #index=index is the keyword to change the index
series4


101    10
102    20
103    30
104    40
105    50
Name: Number Series, dtype: int32

In [23]:
#what different attributes are there?
# Print the index of the Series 
print("Index of the Series:", series4.index)

# Print the values of the Series
print("Values of the Series:", series4.values)

# Print the data type of the elements in the Series
print("Data type of the Series:", series4.dtype)

# Print the shape of the Series
print("Shape of the Series:", series4.shape)

# Print the size (number of elements) in the Series
print("Size (number of elements) of the Series:", series4.size)

# Assign a name to the Series and print it
series4.name = "My Series"
print("Name of the Series", series4.name)


Index of the Series: RangeIndex(start=101, stop=106, step=1)
Values of the Series: [10 20 30 40 50]
Data type of the Series: int32
Shape of the Series: (5,)
Size (number of elements) of the Series: 5
Name of the Series My Series


In [29]:
data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
#index = range(101,106)
series4 = pd.Series(data, index=index, dtype='int32', name="Number Series")
series4 
#Access an element using integer index use iloc if you assign string labeling for index
print("Element at index 0 (integer indexing):", series4.iloc[0]) #Output 10

#Access an element using Label index
print("Element at index 'a' (label indexing):", series4['a']) #Output 10


Element at index 0 (integer indexing): 10
Element at index 'a' (label indexing): 10


In [30]:
print("Slicing :", series4.iloc[1:4]) 

Slicing : b    20
c    30
d    40
Name: Number Series, dtype: int32


In [31]:
print("Slicing :\n", series4.iloc[::2]) 

Slicing :
 a    10
c    30
e    50
Name: Number Series, dtype: int32


In [32]:
print("Slicing :\n", series4.iloc[1::4]) 

Slicing :
 b    20
Name: Number Series, dtype: int32


In [33]:
print("Slicing :\n", series4.iloc[1:4]) 

Slicing :
 b    20
c    30
d    40
Name: Number Series, dtype: int32


In [34]:
series5 = series4 +2
print("Series after multiplying each element by 2:")
print(series5) # Output: [20 40 60 80 100]

Series after multiplying each element by 2:
a    12
b    22
c    32
d    42
e    52
Name: Number Series, dtype: int32


In [37]:
#Sorting
sorted_series = series4.sort_values()
print("Series sorted by values (ascending):")
print(sorted_series)


Series sorted by values (ascending):
a    10
b    20
c    30
d    40
e    50
Name: Number Series, dtype: int32


In [38]:
#Sorting by values (ascending)
sorted_series = series4.sort_values(ascending=False)
print("Series sorted by values (ascending):")
print(sorted_series)


Series sorted by values (ascending):
e    50
d    40
c    30
b    20
a    10
Name: Number Series, dtype: int32


In [39]:
#Sorting by values (descending)
sorted_series = series4.sort_values(ascending=True)
print("Series sorted by values (ascending):")
print(sorted_series)

Series sorted by values (ascending):
a    10
b    20
c    30
d    40
e    50
Name: Number Series, dtype: int32


In [40]:
data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64


In [42]:
data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)
series1.dropna()
print(series1)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64


In [45]:
#to remove items use dropna(). If you remove the index will change also!

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)
series12 = series1.dropna()
print(series1)
print(series12)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
3    40.0
4    50.0
dtype: float64


In [49]:
#To rearrange the index.
#This method however transforms the data for two dimensions
# I am assigning and the original database is not changing

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series12 = series1.dropna()
print(series1)
print(type(series12))

series12=series12.reset_index()
print(series12)
print(type(series12))

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
<class 'pandas.core.series.Series'>
   index     0
0      0  10.0
1      1  20.0
2      3  40.0
3      4  50.0
<class 'pandas.core.frame.DataFrame'>


In [51]:
#If I do not want to maintain original one
#When I do not want the data to change to two dimensions
# I am assigning and the original database is not changing

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series12 = series1.dropna()
print(series1)
print(type(series12))

series12=series12.reset_index(drop=True)
print(series12)
print(type(series12))

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
<class 'pandas.core.series.Series'>
0    10.0
1    20.0
2    40.0
3    50.0
dtype: float64
<class 'pandas.core.series.Series'>


In [52]:
#To change the original database

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series12 = series1.dropna()
print(series1)
print(type(series12))

series12.reset_index(drop=True, inplace=True)
print(series12)
print(type(series12))


0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
<class 'pandas.core.series.Series'>
0    10.0
1    20.0
2    40.0
3    50.0
dtype: float64
<class 'pandas.core.series.Series'>


In [55]:
#To change the original database

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series1.dropna(inplace=True)
print(series1)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
3    40.0
4    50.0
dtype: float64


In [57]:
#I also can change the original index
#To change the original database

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series1.dropna(inplace=True)
series1.reset_index(inplace=True) #this creates an error because is trying to create a two dimension object that cannot fit in one dimension object of Series
print(series1)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64


TypeError: Cannot reset_index inplace on a Series to create a DataFrame

In [59]:
#I also can change the original index
#To change the original database

#To resolve the case before use drop on series1.reset_index(inplace=True, drop=True) because I do not want to retain a copy of the previous database

data = [10, 20, None, 40, 50]
series1 = pd.Series(data)
print(series1)

series1.dropna(inplace=True)
series1.reset_index(inplace=True, drop=True) #this creates an error because is trying to create a two dimension object that cannot fit in one dimension object of Series
print(series1)

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64
0    10.0
1    20.0
2    40.0
3    50.0
dtype: float64


In [60]:
#Previous was about Series now lets explore about Data Frame
# Data Frames require a two dimension data
# Cannot convert a single list. Single list only converts into Series only
# Pandas offers multiple ways to create a DataFrame, depending on the type and structure of the data you have

# From a Dictionary of Lists
# Each key in the dictionary represents a column name, and the values (lists) are the data for that column.
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [61]:
# From a List of Dictionaries
# Important APIs will give you the data in this format!
# Each dictionary in the list represents a row of data, with keys as column names.
data = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "Los Angeles"},
    {"Name": "Charlie", "Age": 35, "City": "Chicago"}
]

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [62]:
# From a List of Lists (with Column Names). You can create a DataFrame from a list of lists and specify the column names separately.
#Unlabelled data (doesnt have labels)
data = [
    ["Alice", 25, "New York"],
    ["Bob", 30, "Los Angeles"],
    ["Charlie", 35, "Chicago"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [84]:
# Attributes of a DataFrame. Creating a summarised report

print("Attributes os a DataFrame:")
print("Columns:", df.columns) # Returns the column labels
print("Index:", df.index) #Returns the index labels
print("Shape:", df.shape) # Returns the shape of the DtaFrame (rows, columns)
print("Data Types:", df.dtypes) # Returns the data types of the columns
print("Info 9summary):")
df.info() # Asummary of the DataFrame with non-null count and data types 
print()

Attributes os a DataFrame:
Columns: Index(['Name', 'Age', 'City'], dtype='object')
Index: RangeIndex(start=0, stop=3, step=1)
Shape: (3, 3)
Data Types: Name    object
Age      int64
City    object
dtype: object
Info 9summary):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes



In [85]:
df.info() #recalling the info quickly

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [63]:
#From a NumPy Array. You can use a NumPy array to populate the DataFrame and provide column names.
import numpy as np

data = np.array([
    ["Alice", 25, "New York"],
    ["Bob", 30, "Los Angeles"],
    ["Charlie", 35, "Chicago"]
])

df = pd.DataFrame(data, columns=["Name", "Age", "City"])
print(df)

      Name Age         City
0    Alice  25     New York
1      Bob  30  Los Angeles
2  Charlie  35      Chicago


In [64]:
# From a Dictionary of Series. Each Series object represents a column, and the keys represent the column names.
# The length has to be the same everywhere (in this case 3... so it couldnt be 'Age': 925,30), because it would give an error
data = {
    "Name": pd.Series(["Alice", "Bob", "Charlie"]),
    "Age": pd.Series([25, 30, 35]),
    "City": pd.Series(["New York", "Los Angeles", "Chicago"])
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [69]:
df

Name  Age     City
0    Alice   30  Unknown
1      Bob   30  Unknown
2  Charlie   30  Unknown

In [70]:
#Two types of Indexing

df.index

RangeIndex(start=0, stop=3, step=1)

In [71]:
#Two types of Indexing

df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [72]:
df.loc[0] #locating the items

Name      Alice
Age          30
City    Unknown
Name: 0, dtype: object

In [73]:
df.loc[1] #locating the items

Name        Bob
Age          30
City    Unknown
Name: 1, dtype: object

In [74]:
df.loc[1, 'Name']

'Bob'

In [75]:
df.loc[0, 'Name']

'Alice'

In [76]:
#Returning the entire row
df.loc[1]

Name        Bob
Age          30
City    Unknown
Name: 1, dtype: object

In [77]:
# Accessing columns only (loc can'te be used here)

df[['Name', 'Age']]

Name  Age
0    Alice   30
1      Bob   30
2  Charlie   30

In [78]:
# Accessing a single columns only (loc can'te be used here)

df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [83]:
#Using slicing to access

df.iloc[2,0]

'Charlie'

In [66]:
# From a CSV File. You can create a DataFrame by reading data from a CSV file using the pd.read_csv() method.
# df = pd.read_csv("data.csv")
# df.info()
# print(df)

# From an Excel File. Use pd.read_excel() to create a DataFrame from an Excel file.
# df = pd.read_excel("data.xlsx")
# print(df)

# From a JSON File. You can also load data from a JSON file using pd.read_json().
#df = pd.read_json("data.json")
# print(df)

# From a Zip File or Multiple Sources
# Pandas can handle compressed files or URLs directly. For instance:

# df = pd.read_csv("data.zip") 
# or
df = pd.read_csv("https://dummyjson.com/products")
print(df)

Empty DataFrame
Columns: [{"products":[{"id":1, title:"Essence Mascara Lash Princess", description:"The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.", category:"beauty", price:9.99, discountPercentage:7.17, rating:4.94, stock:5, tags:["beauty", mascara], brand:"Essence", sku:"RCH45Q1A", weight:2, dimensions:{"width":23.17, height:14.43, depth:28.01}, warrantyInformation:"1 month warranty", shippingInformation:"Ships in 1 month", availabilityStatus:"Low Stock", reviews:[{"rating":2, comment:"Very unhappy with my purchase!", date:"2024-05-23T08:56:21.618Z", reviewerName:"John Doe", reviewerEmail:"john.doe@x.dummyjson.com"}, {"rating":2, comment:"Not as described!", date:"2024-05-23T08:56:21.618Z".1, reviewerName:"Nolan Gonzalez", reviewerEmail:"nolan.gonzalez@x.dummyjson.com"}, {"rating":5, comment:"Very satisfied!", date:"2024-05-23T08:56:21.618Z".2, reviewerN

In [67]:
# From Scalars or Default Values. You can initialize a DataFrame with default values or scalar values.
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": 30,  # A scalar value is broadcast to all rows
    "City": "Unknown"
})
print(df)

      Name  Age     City
0    Alice   30  Unknown
1      Bob   30  Unknown
2  Charlie   30  Unknown


In [68]:
# From Existing DataFrames. You can create a new DataFrame by slicing or copying another DataFrame.
original_df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
})

# Slicing to create a new DataFrame
new_df = original_df[["Name", "City"]]
print(new_df)


      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago


In [ ]:
# Summary Table of Methods:
# Method	Example Syntax

# Dictionary of Lists	pd.DataFrame(data_dict)
# List of Dictionaries	pd.DataFrame(list_of_dicts)
# List of Lists	pd.DataFrame(list_of_lists, columns=...)
# NumPy Array	pd.DataFrame(np_array, columns=...)
# Dictionary of Series	pd.DataFrame(data_dict_of_series)
# CSV File	pd.read_csv("file.csv")
# Excel File	pd.read_excel("file.xlsx")
# JSON File	pd.read_json("file.json")
# Scalars	pd.DataFrame({"col1": scalar_value})

# NumPy (short for Numerical Python) is a Python library used for scientific computing and data manipulation. It's widely considered the foundational package for numerical computing in Python because of its powerful capabilities for handling arrays and performing mathematical operations efficiently.


In [86]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root";
    password="root",
    database="mydb",
)

In [87]:
df = pd.read_sql("select * from product", conn)
df

NameError: name 'conn' is not defined

In [89]:
# Sending a request to retrieve a dabase from 
#Web scrapping - Live website or APIs (despite you need a request module for this)
import requests
response = requests.get("https://dummyjson.com/products")
response 


<Response [200]>

In [90]:
# Sending a request to retrieve a dabase from 
#Web scrapping - Live website or APIs (despite you need a request module for this)
import requests
response = requests.get("https://dummyjson.com/products")
json_data = response.json()
json_data

{'products': [{'id': 1,
   'title': 'Essence Mascara Lash Princess',
   'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
   'category': 'beauty',
   'price': 9.99,
   'discountPercentage': 7.17,
   'rating': 4.94,
   'stock': 5,
   'tags': ['beauty', 'mascara'],
   'brand': 'Essence',
   'sku': 'RCH45Q1A',
   'weight': 2,
   'dimensions': {'width': 23.17, 'height': 14.43, 'depth': 28.01},
   'warrantyInformation': '1 month warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'Low Stock',
   'reviews': [{'rating': 2,
     'comment': 'Very unhappy with my purchase!',
     'date': '2024-05-23T08:56:21.618Z',
     'reviewerName': 'John Doe',
     'reviewerEmail': 'john.doe@x.dummyjson.com'},
    {'rating': 2,
     'comment': 'Not as described!',
     'date': '2024-05-23T08:56:21.618Z',
     'reviewerName': 'Nolan Gon

In [91]:
# Sending a request to retrieve a dabase from 
#Web scrapping - Live website or APIs (despite you need a request module for this)
import requests
response = requests.get("https://dummyjson.com/products")
json_data = response.json()
type(json_data)

dict

In [93]:
df = pd.DataFrame(json_data)
df

products  total  skip  limit
0   {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1   {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2   {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3   {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4   {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30
5   {'id': 6, 'title': 'Calvin Klein CK One', 'des...    194     0     30
6   {'id': 7, 'title': 'Chanel Coco Noir Eau De', ...    194     0     30
7   {'id': 8, 'title': 'Dior J'adore', 'descriptio...    194     0     30
8   {'id': 9, 'title': 'Dolce Shine Eau de', 'desc...    194     0     30
9   {'id': 10, 'title': 'Gucci Bloom Eau de', 'des...    194     0     30
10  {'id': 11, 'title': 'Annibale Colombo Bed', 'd...    194     0     30
11  {'id': 12, 'title': 'Annibale Colombo Sofa', '...    194     0     30
12  {'id': 13, 'title': 'Bedside Table African Che...    194     0     30
13  {'id': 14, 'title': 'Knoll Saarinen Executive ...    194     0     30
14  {'id': 15, 'title': 'Wooden Bathroom Sink With...    194     0     30
15  {'id': 16, 'title': 'Apple', 'description': 'F...    194     0     30
16  {'id': 17, 'title': 'Beef Steak', 'description...    194     0     30
17  {'id': 18, 'title': 'Cat Food', 'description':...    194     0     30
18  {'id': 19, 'title': 'Chicken Meat', 'descripti...    194     0     30
19  {'id': 20, 'title': 'Cooking Oil', 'descriptio...    194     0     30
20  {'id': 21, 'title': 'Cucumber', 'description':...    194     0     30
21  {'id': 22, 'title': 'Dog Food', 'description':...    194     0     30
22  {'id': 23, 'title': 'Eggs', 'description': 'Fr...    194     0     30
23  {'id': 24, 'title': 'Fish Steak', 'description...    194     0     30
24  {'id': 25, 'title': 'Green Bell Pepper', 'desc...    194     0     30
25  {'id': 26, 'title': 'Green Chili Pepper', 'des...    194     0     30
26  {'id': 27, 'title': 'Honey Jar', 'description'...    194     0     30
27  {'id': 28, 'title': 'Ice Cream', 'description'...    194     0     30
28  {'id': 29, 'title': 'Juice', 'description': 'R...    194     0     30
29  {'id': 30, 'title': 'Kiwi', 'description': 'Nu...    194     0     30

In [94]:
# Sending a request to retrieve a dabase from 
#Web scrapping - Live website or APIs (despite you need a request module for this)
import requests
response = requests.get("https://dummyjson.com/products")
json_data = response.json()
json_data['products']

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 7.17,
  'rating': 4.94,
  'stock': 5,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'RCH45Q1A',
  'weight': 2,
  'dimensions': {'width': 23.17, 'height': 14.43, 'depth': 28.01},
  'warrantyInformation': '1 month warranty',
  'shippingInformation': 'Ships in 1 month',
  'availabilityStatus': 'Low Stock',
  'reviews': [{'rating': 2,
    'comment': 'Very unhappy with my purchase!',
    'date': '2024-05-23T08:56:21.618Z',
    'reviewerName': 'John Doe',
    'reviewerEmail': 'john.doe@x.dummyjson.com'},
   {'rating': 2,
    'comment': 'Not as described!',
    'date': '2024-05-23T08:56:21.618Z',
    'reviewerName': 'Nolan Gonzalez',
    'reviewerEmail': 'nolan.g

In [3]:
# To retrieve rows
import pandas as pd  # Make sure to import pandas at the top

# Read the CSV file
df = pd.read_csv("hurricanes.csv")
df

Month   "Average"   "2005"   "2006"   "2007"   "2008"   "2009"   "2010"  \
0   May         0.1        0        0        1        1        0        0   
1   Jun         0.5        2        1        1        0        0        1   
2   Jul         0.7        5        1        1        2        0        1   
3   Aug         2.3        6        3        2        4        4        4   
4   Sep         3.5        6        4        7        4        2        8   
5   Oct         2.0        8        0        1        3        2        5   
6   Nov         0.5        3        0        0        1        1        0   
7   Dec         0.0        1        0        1        0        0        0   

    "2011"   "2012"   "2013"   "2014"   "2015"  
0        0        2        0        0        0  
1        1        2        2        0        1  
2        3        0        2        2        1  
3        7        8        2        2        3  
4        5        2        5        2        5  
5        1        5        2        3        0  
6        1        0        1        0        1  
7        0        0        0        0        1

In [6]:
# Display the first 20 rows
df.head(20)

# Display the last 3 rows
df.tail(3)

# Randomly sample 3 rows
df.sample(3)

# Retrieve rows with labels from 2 to 6 (inclusive)
df.loc[2:6]

# Retrieve every 6th row
df.loc[::6]

Month   "Average"   "2005"   "2006"   "2007"   "2008"   "2009"   "2010"  \
0   May         0.1        0        0        1        1        0        0   
6   Nov         0.5        3        0        0        1        1        0   

    "2011"   "2012"   "2013"   "2014"   "2015"  
0        0        2        0        0        0  
6        1        0        1        0        1

In [8]:
# Retrieve every 2nd row and specific columns (correcting duplicate column name)
# df.loc[::2, ['name']]


# Retrieve every 2nd row and specific columns using positional indexing
df.iloc[::2, [0, 2]]  # Corrected to use a list for column positions


Month   "2005"
0   May        0
2   Jul        5
4   Sep        6
6   Nov        3

In [9]:

# Summary statistics for numerical columns
df.describe()


"Average"    "2005"    "2006"    "2007"    "2008"    "2009"    "2010"  \
count   8.000000  8.000000  8.000000  8.000000  8.000000  8.000000  8.000000   
mean    1.200000  3.875000  1.125000  1.750000  1.875000  1.125000  2.375000   
std     1.254705  2.799872  1.552648  2.187628  1.642081  1.457738  2.973094   
min     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
25%     0.400000  1.750000  0.000000  1.000000  0.750000  0.000000  0.000000   
50%     0.600000  4.000000  0.500000  1.000000  1.500000  0.500000  1.000000   
75%     2.075000  6.000000  1.500000  1.250000  3.250000  2.000000  4.250000   
max     3.500000  8.000000  4.000000  7.000000  4.000000  4.000000  8.000000   

        "2011"    "2012"    "2013"    "2014"    "2015"  
count  8.00000  8.000000  8.000000  8.000000  8.000000  
mean   2.25000  2.375000  1.750000  1.125000  1.500000  
std    2.54951  2.825269  1.581139  1.246423  1.690309  
min    0.00000  0.000000  0.000000  0.000000  0.000000  
25%    0.75000  0.000000  0.750000  0.000000  0.750000  
50%    1.00000  2.000000  2.000000  1.000000  1.000000  
75%    3.50000  2.750000  2.000000  2.000000  1.500000  
max    7.00000  8.000000  5.000000  3.000000  5.000000

In [11]:

# Value counts for a specific column (provide the column name)
df['Month'].value_counts()  # Replace 'ColumnName' with the name of the column


Month
May    1
Jun    1
Jul    1
Aug    1
Sep    1
Oct    1
Nov    1
Dec    1
Name: count, dtype: int64

In [12]:
# Get value counts for the entire DataFrame (not typical, but it works on rows as tuples)
obj = df.value_counts()
print(type(obj))  # Check the type of the resulting object
print(obj)        # Display the result


<class 'pandas.core.series.Series'>
Month   "Average"   "2005"   "2006"   "2007"   "2008"   "2009"   "2010"   "2011"   "2012"   "2013"   "2014"   "2015"
Aug    2.3         6        3        2        4        4        4        7        8        2        2        3          1
Dec    0.0         1        0        1        0        0        0        0        0        0        0        1          1
Jul    0.7         5        1        1        2        0        1        3        0        2        2        1          1
Jun    0.5         2        1        1        0        0        1        1        2        2        0        1          1
May    0.1         0        0        1        1        0        0        0        2        0        0        0          1
Nov    0.5         3        0        0        1        1        0        1        0        1        0        1          1
Oct    2.0         8        0        1        3        2        5        1        5        2        3        0     

In [13]:
# Get value counts for a specific column (e.g., 'Location')
obj = df['Month'].value_counts()
print(type(obj))  # Check the type of the resulting object
print(obj)        # Display the result


<class 'pandas.core.series.Series'>
Month
May    1
Jun    1
Jul    1
Aug    1
Sep    1
Oct    1
Nov    1
Dec    1
Name: count, dtype: int64
