In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]

In [3]:
my_array = np.array(my_list)

In [4]:
my_array

array([1, 2, 3, 4, 5])

In [5]:
import random
import numpy as np

# Generate a random integer between 1 and 10 using random module
print(random.randint(1, 10))

# Generate a 3x3 array of random integers between 1 and 10 using NumPy
rand_int = np.random.randint(1, 10, size=(3, 3))

# Print the random integer array
print("Random Integer Array:\n", rand_int)

9
Random Integer Array:
 [[3 8 8]
 [5 8 5]
 [8 7 3]]


In [6]:
rand_float = np.random.random((2,2))
print("Random Float Array:\n", rand_float)

Random Float Array:
 [[0.89586107 0.9974724 ]
 [0.39325099 0.77447379]]


In [7]:
normal_dist = np.random.randn(3, 3)
print("normal Distribution Array:\n", normal_dist)

normal Distribution Array:
 [[ 1.07500822  0.29528844 -0.06953621]
 [-0.70449717  0.42519179  0.58866997]
 [ 1.11906971 -2.63058313 -0.54408195]]


In [8]:
arr_arange = np.arange(1, 10, 1).reshape(3,3)
print("\nArange array (range with step):\n", arr_arange)


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr_arange = np.arange(1, 10, 1).reshape(3,3)
print("\nArange array (range with step):\n", arr_arange)
print("index ", arr_arange[5])
print("slice ", arr_arange{1:6])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '{' (1710407192.py, line 4)

In [11]:
import numpy as np
arr_arange = np.arange(1, 10, 1).reshape(3, 3)
print("\nArange array (range with step):\n", arr_arange)
print("index [1, 2]:", arr_arange[1, 2])  
print("slice (rows 1 to 2, columns 1 to 2):\n", arr_arange[1:3, 0:2])  


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
index [1, 2]: 6
slice (rows 1 to 2, columns 1 to 2):
 [[4 5]
 [7 8]]


In [12]:
arr_arange = np.arange(1, 10, 1)
print("\nArange array (range with step):\n", arr_arange)
print("index ", arr_arange[5])
print("slice ", arr_arange[1:6])
print("slice ", arr_arange[:6])
print("slice ", arr_arange[2:])



Arange array (range with step):
 [1 2 3 4 5 6 7 8 9]
index  6
slice  [2 3 4 5 6]
slice  [1 2 3 4 5 6]
slice  [3 4 5 6 7 8 9]


In [13]:
arr_arange = np.arange(1, 10, 1).reshape(3,3)
print("\nArange array (range with step):\n", arr_arange)
print(arr_arange[1])
print(arr_arange[1,1])
print(arr_arange[:,1])
print(arr_arange[::2,::2]) #[start=0:end=len(array):step=1]


Arange array (range with step):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
5
[2 5 8]
[[1 2]
 [4 5]]


In [14]:
arr1 = arr_arange[::2,::2]
print(arr1)
arr2 = arr_arange[:2:1,:2:1]
print(arr2)

[[1 3]
 [7 9]]
[[1 2]
 [4 5]]


In [15]:
arr1 = arr2 + 5
print(arr2)

[[1 2]
 [4 5]]


In [17]:
arr1 = arr2 + np.array([1,2])
print(arr1)
print(arr2)

[[2 4]
 [5 7]]
[[1 2]
 [4 5]]


In [18]:
l1 = [5,6,7,4, "Jay", False, (5,6)]

In [19]:
print(l1)

[5, 6, 7, 4, 'Jay', False, (5, 6)]
